# Generated by Django 3.2.3 on 2021-05-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeslist',
            old_name='subscribe',
            new_name='subscribed_to',
        ),
    ]
