# Generated by Django 3.2.3 on 2021-05-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_subscribe_subscribeslist_subscribed_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeslist',
            name='subscribed_to',
        ),
        migrations.AddField(
            model_name='subscribeslist',
            name='subscribed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscribe'),
        ),
    ]
