# Generated by Django 3.2.3 on 2021-05-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210517_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeslist',
            name='subscribed_to',
        ),
        migrations.AddField(
            model_name='subscribeslist',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, to='accounts.Subscribe'),
        ),
    ]
