# Generated by Django 3.2.3 on 2021-05-20 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_subscribe_subscribeslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadedPostsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('were_read', models.ManyToManyField(blank=True, to='blog.Post')),
            ],
        ),
    ]
