# Generated by Django 3.2.3 on 2021-05-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_readedpostslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readed_time', models.DateTimeField(auto_now_add=True, verbose_name='subscribed_time')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
        migrations.AlterField(
            model_name='readedpostslist',
            name='were_read',
            field=models.ManyToManyField(blank=True, to='blog.ReadedPost'),
        ),
    ]
